# Generated by Django 5.1 on 2024-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactemaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactemaillist',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
