# Generated by Django 5.1 on 2024-09-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactemaillist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactemaillist',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='name',
            new_name='full_name',
        ),
    ]
