# Generated by Django 5.1 on 2024-09-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_name_contactemaillist_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactemaillist',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactemaillist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='user',
        ),
    ]
