# Generated by Django 5.1 on 2024-09-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_rename_full_name_contactemaillist_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactEmailList',
        ),
    ]
