# Generated by Django 5.1 on 2024-09-16 16:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_room'),
        ('worlds', '0006_alter_room_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(choices=[('MEDIEVAL CASTLE', 'MEDIEVAL CASTLE'), ('RENAISSANCE VILLA', 'RENAISSANCE VILLA'), ('VICTORIAN MANSION', 'VICTORIAN MANSION'), ('DRACULA CASTLE', 'DRACULA CASTLE'), ('FAIRY FOREST', 'FAIRY FOREST')], max_length=100)),
                ('category', models.CharField(choices=[('MED', 'Medieval'), ('REN', 'Renaissance'), ('VIC', 'Victorian'), ('DRA', 'Dracula'), ('FAF', 'Fairy Forest')], max_length=3)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_dinning', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
