# Generated by Django 5.1 on 2024-09-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_world_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='category',
        ),
    ]
