# Generated by Django 5.1 on 2024-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_remove_world_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='image_dinning',
            new_name='image_dining',
        ),
        migrations.AddField(
            model_name='world',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
