# Generated by Django 5.1 on 2024-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0009_rename_image_dinning_world_image_dining_world_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='display_name',
            field=models.CharField(choices=[('medieval_castle', 'MEDIEVAL CASTLE'), ('renaissance_villa', 'RENAISSANCE VILLA'), ('victorian_mansion', 'VICTORIAN MANSION'), ('dracula_castle', 'DRACULA CASTLE'), ('fairy_forest', 'FAIRY FOREST')], max_length=100),
        ),
    ]
