# Generated by Django 5.1 on 2024-09-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0010_alter_world_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='display_name',
            field=models.CharField(choices=[('MEDIEVAL CASTLE', 'MEDIEVAL CASTLE'), ('RENAISSANCE VILLA', 'RENAISSANCE VILLA'), ('VICTORIAN MANSION', 'VICTORIAN MANSION'), ('DRACULA CASTLE', 'DRACULA CASTLE'), ('FAIRY FOREST', 'FAIRY FOREST')], max_length=100),
        ),
    ]
