# Generated by Django 5.1 on 2024-09-16 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0011_alter_world_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='world',
            name='image_dining',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
