# Generated by Django 5.1 on 2024-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_alter_world_image_alter_world_image_dining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='display_name',
            field=models.CharField(choices=[('MEDIEVAL CASTLE', 'MEDIEVAL CASTLE'), ('RENAISSANCE VILLA', 'RENAISSANCE VILLA'), ('VICTORIAN MANSION', 'VICTORIAN MANSION'), ('DRACULA CASTLE', 'DRACULA CASTLE'), ('FAIRY FOREST', 'FAIRY FOREST')], default='noname', max_length=100),
        ),
    ]
