# Generated by Django 5.1 on 2024-09-16 20:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_alter_world_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='image_jakuzzi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
