# Generated by Django 5.1 on 2024-09-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0014_world_image_jakuzzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='short_description',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
