# Generated by Django 5.1 on 2024-09-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_world_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='short_description',
            field=models.TextField(),
        ),
    ]
