# Generated by Django 5.1 on 2024-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0016_alter_world_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='short_description',
            field=models.TextField(default='noname'),
        ),
    ]
