# Generated by Django 5.1 on 2024-09-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0017_alter_world_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='display_name',
            field=models.CharField(default='noname', max_length=100),
        ),
    ]
