# Generated by Django 5.1 on 2024-09-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0018_alter_world_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='image',
            new_name='image_siesta',
        ),
    ]
