# Generated by Django 5.1 on 2024-09-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0019_rename_image_world_image_siesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['display_name']},
        ),
    ]
