# Generated by Django 5.1 on 2024-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='company_name',
            field=models.CharField(default='company', max_length=200),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='message',
            field=models.TextField(max_length=80),
        ),
    ]
