# Generated by Django 5.1 on 2024-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
