# Generated by Django 5.1 on 2024-09-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_collaboraterequest_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
