# Generated by Django 5.1 on 2024-09-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_collaboraterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profile_image',
            new_name='image',
        ),
    ]
