# Generated by Django 5.1 on 2024-09-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_room'),
        ('worlds', '0007_world_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worlds.world'),
        ),
    ]
