# Generated by Django 5.1 on 2024-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.CharField(choices=[('10:00', '10:00 AM - 05:00 PM'), ('18:00', '07:00 PM - 08:00 AM')], max_length=5),
        ),
    ]
