# Generated by Django 5.1 on 2024-09-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='start_time',
            new_name='time',
        ),
    ]
