# Generated by Django 5.1 on 2024-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_start_time_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10 am - 5 pm', '10 am - 5 pm'), ('7 pm - 8 am', '7 pm - 8 am')], max_length=19),
        ),
    ]
